### ISSUE TITLE
Unable to learn battle styles

### ISSUE THREAD

**Issue by EpicEnder** [Forixaim/Epic-Fight-Battle-Arts#12]
After I open a book and hit the learn button there are no slots for me to select in order to equip the skill. I'm on a modpack, so I understand if it's too much of a hassle but I just wanted to know if there was an easy fix.
[RPG.zip](https://github.com/user-attachments/files/15506571/RPG.zip)

![image_2024-05-30_185837129](https://github.com/Forixaim/Epic-Fight-Battle-Styles/assets/79155755/941fedfd-132f-4799-bd79-d6d8bb1561d3)

**Comment by Forixaim** [comment]
Sorry for the late reply,

School's recently out for me so I can help you fix this issue that has plagued most modpacks.

I've downloaded your modpack to test out the problems and hope to reproduce some of the errors.
