### ISSUE TITLE
crash java.lang.ArrayIndexOutOfBoundsException: Index 14 out of bounds for length 12

### ISSUE THREAD

**Issue by maximogta** [Forixaim/Epic-Fight-Battle-Arts#13]
When joining a world my game crashes and i get "java.lang.ArrayIndexOutOfBoundsException: Index 14 out of bounds for length 12" 
[latest.log](https://github.com/user-attachments/files/15928025/latest.log)
Issue since 1.1.5, happens in 1.2.0 too.

**Comment by Forixaim** [comment]
Thanks for the issue,

![image](https://github.com/Forixaim/Epic-Fight-Battle-Styles/assets/59586922/359862b7-6288-4816-b091-f4e652bd9155)

This little thing here is the main problem.

The extra Skill Slots I've added didn't fully register and therefore messed up the ExtendableEnumManager.

This is a problem I have to myself report to Yesman.

**Comment by Forixaim** [comment]
Update

Yesman has fixed the issue on his end and we all live happily ever after.
